### ISSUE TITLE
Figure this out

### ISSUE THREAD

**Issue by trtstm** [mailmoose/mailmoose#13]
This command keeps the server waiting for a command. Even if I type a newline manually.

```
echo -ne 'helo' | nc localhost 2525
```

Don't know if it's netcat or our server's problem.

**Comment by DenBeke** [comment]
Why wouldn't it be waiting?

**Comment by trtstm** [comment]
it should but if I type a newline after it it still waits.

**Comment by DenBeke** [comment]
And telnet?
