### ISSUE TITLE
Config management

### ISSUE THREAD

**Issue by DenBeke** [mailmoose/mailmoose#36]
We need to work on how we store config in `main.go` to make it available for other component like e.g. the handlers.

**Comment by DenBeke** [comment]
For now I made the `c` config variable global in `main.go`

**Comment by DenBeke** [comment]
Package `config`:

    LoadConfig()
    SaveConfig()

Contains object/interface `config`:

    get(key string)
    put(key string, value string)

Pass the config object to functions/components/... or make it accessible in singleton? How then? @trtstm

**Comment by trtstm** [comment]
Passing ;)
